<?php

function kiv_sortering_views_pre_render(&$view) {
	// If there are more than 100 results, show a message that encourages the user
	// to change the filter settings.
	// (This action could be performed later in the execution process, but not
	// earlier.)
	
	dpm($view, __FUNCTION__);
	$view->items_per_page = '10';
	$view->current_display   = 'page';
	//START---------------------------------------------------------------------------------------------------------
	//---------------------------------------------------------------------------------------------------------
	/// kör sortering endast om något finns att sortera i requested Category
	if(isset($view->build_info['substitutions']['%1'])){
		
		$mainCategory = $view->build_info['substitutions']['%1']; // visar av användaren vald kategori
		
		//---------------------------------------------------------------------------------------------------------
		// Array:erna ---------------------------------------------------------------------------------------------  
		$MainCategoryReturnArray = array();
		$MainCategoryArray= array();
		$RelatedCategoryArray= array();
		//---------------------------------------------------------------------------------------------------------
		
		//---------------------------------------------------------------------------------------------------------
		// vy datat innehåller hela listan osorterad  
		$arrViewResult = $view->result;
		//---------------------------------------------------------------------------------------------------------
		
		//---------------------------------------------------------------------------------------------------------
		// lägg till alla fält in i MainCategoryReturnArray där huvudkategorin är av användaren vald kategori 
		foreach($arrViewResult as $tmpMcat)  {
			$valdcat = $tmpMcat->field_field_category['0']['rendered']['#title'];
			
			if($valdcat == $mainCategory){
				array_push($MainCategoryArray,$tmpMcat);
				//print($view->build_info['substitutions']['%1']. '<br />');
			}				
		}		
		//---------------------------------------------------------------------------------------------------------
		
		
		//---------------------------------------------------------------------------------------------------------
		// lägg till alla fält in i $RelatedCategoryArray där relaterade kategorier är lika med av användaren vald kategori 
		foreach($arrViewResult as $tmpMcat)  {
			
			$tmpAddToArr= 0;
			
			//gå igenom alla items i arrayen och se om någon matchar valdcategori
			foreach( $tmpMcat->field_field_underomr_de as $tmpUnderCat){ 
				
				if($tmpUnderCat['rendered']['#title'] == $mainCategory){
					$tmpAddToArr= 1;
					break; 
				}				
			}
			if($tmpAddToArr== 1){
				array_push($RelatedCategoryArray,$tmpMcat);
			}			
		}
		//---------------------------------------------------------------------------------------------------------
		
		
		//---------------------------------------------------------------------------------------------------------
		//Slå ihop arrayerna så att maincategory kommer överst och dom relaterade efter		
		$MainCategoryReturnArray = array_merge($MainCategoryArray, $RelatedCategoryArray);
		//---------------------------------------------------------------------------------------------------------
		
		
		//---------------------------------------------------------------------------------------------------------
		//Returnera Den nysorterade datan 
		$view->result = $MainCategoryReturnArray;
		//---------------------------------------------------------------------------------------------------------
		
	}// isset END	
	
} // Function END

/**
 * @file
 * .
 *
 *
 * @author SVEN ÄNGERMARK och ANDREAS JOSEFSSON 2015>
 */
//Exmpel
// D
function kiv_sortering_views_query_alter(&$view, &$query) {
	dpm($view, __FUNCTION__);
	dpm($query, __FUNCTION__);
	$view->items_per_page = '10';
	$view->current_display   = 'page';
	
}
